name: imageclassenv2
Channels:
  - conda-forge
  - defaults
Platform: win-64
dependencies:
  - _tflow_select=2.3.0=mkl
  - absl-py=2.1.0=pyhd8ed1ab_0
  - aiohttp=3.9.5=py39ha55989b_0
  - aiosignal=1.3.1=pyhd8ed1ab_0
  - anyio=4.3.0=pyhd8ed1ab_0
  - argon2-cffi=23.1.0=pyhd8ed1ab_0
  - argon2-cffi-bindings=21.2.0=py39ha55989b_4
  - arrow=1.3.0=pyhd8ed1ab_0
  - asttokens=2.4.1=pyhd8ed1ab_0
  - astunparse=1.6.3=pyhd8ed1ab_0
  - async-lru=2.0.4=pyhd8ed1ab_0
  - async-timeout=4.0.3=pyhd8ed1ab_0
  - attrs=23.2.0=pyh71513ae_0
  - aws-c-auth=0.6.1=h25973b9_0
  - aws-c-cal=0.5.11=he19cf47_0
  - aws-c-common=0.6.2=h8ffe710_0
  - aws-c-compression=0.2.13=h1e232aa_0
  - aws-c-event-stream=0.2.7=h70e1b0c_13
  - aws-c-http=0.6.4=h6080af5_9
  - aws-c-io=0.10.5=h2fe331c_0
  - aws-c-mqtt=0.7.6=h60c7eb6_10
  - aws-c-s3=0.1.20=h86bff3a_1
  - aws-checksums=0.1.11=h1e232aa_7
  - aws-crt-cpp=0.14.2=hf85b130_1
  - babel=2.14.0=pyhd8ed1ab_0
  - beautifulsoup4=4.12.3=pyha770c72_0
  - bleach=6.1.0=pyhd8ed1ab_0
  - blinker=1.8.2=pyhd8ed1ab_0
  - brotli-python=1.0.9=py39h99910a6_9
  - bzip2=1.0.8=hcfcfb64_5
  - c-ares=1.28.1=hcfcfb64_0
  - ca-certificates=2024.2.2=h56e8100_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cachetools=5.3.3=pyhd8ed1ab_0
  - certifi=2024.2.2=pyhd8ed1ab_0
  - cffi=1.16.0=py39ha55989b_0
  - charset-normalizer=3.3.2=pyhd8ed1ab_0
  - click=8.1.7=win_pyh7428d3b_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - comm=0.2.2=pyhd8ed1ab_0
  - cryptography=39.0.0=py39h58e9bdb_0
  - debugpy=1.8.1=py39h99910a6_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - entrypoints=0.4=pyhd8ed1ab_0
  - exceptiongroup=1.2.0=pyhd8ed1ab_2
  - executing=2.0.1=pyhd8ed1ab_0
  - flatbuffers=24.3.25=h63175ca_0
  - fqdn=1.5.1=pyhd8ed1ab_0
  - frozenlist=1.4.1=py39ha55989b_0
  - gast=0.4.0=pyh9f0ad1d_0
  - giflib=5.2.2=h64bf75a_0
  - google-auth=2.29.0=pyhca7485f_0
  - google-auth-oauthlib=0.4.6=pyhd8ed1ab_0
  - google-pasta=0.2.0=pyh8c360ce_0
  - grpc-cpp=1.47.1=hcb02dd0_6
  - grpcio=1.47.1=py39hf834a4b_6
  - h11=0.14.0=pyhd8ed1ab_0
  - h2=4.1.0=pyhd8ed1ab_0
  - h5py=3.9.0=nompi_py39h9c8e182_100
  - hdf5=1.14.0=nompi_h97a5375_103
  - hpack=4.0.0=pyh9f0ad1d_0
  - httpcore=1.0.5=pyhd8ed1ab_0
  - httpx=0.27.0=pyhd8ed1ab_0
  - hyperframe=6.0.1=pyhd8ed1ab_0
  - icu=58.2=ha925a31_3
  - idna=3.7=pyhd8ed1ab_0
  - importlib-metadata=7.1.0=pyha770c72_0
  - importlib_metadata=7.1.0=hd8ed1ab_0
  - importlib_resources=6.4.0=pyhd8ed1ab_0
  - intel-openmp=2024.1.0=h57928b3_965
  - ipykernel=6.29.3=pyha63f2e9_0
  - ipywidgets=8.1.2=pyhd8ed1ab_1
  - isoduration=20.11.0=pyhd8ed1ab_0
  - jedi=0.19.1=pyhd8ed1ab_0
  - jinja2=3.1.4=pyhd8ed1ab_0
  - jpeg=9e=h8ffe710_2
  - json5=0.9.25=pyhd8ed1ab_0
  - jsonpointer=2.4=py39hcbf5309_3
  - jsonschema=4.22.0=pyhd8ed1ab_0
  - jsonschema-specifications=2023.12.1=pyhd8ed1ab_0
  - jsonschema-with-format-nongpl=4.22.0=pyhd8ed1ab_0
  - jupyter=1.0.0=pyhd8ed1ab_10
  - jupyter-lsp=2.2.5=pyhd8ed1ab_0
  - jupyter_client=8.6.1=pyhd8ed1ab_0
  - jupyter_console=6.6.3=pyhd8ed1ab_0
  - jupyter_core=5.7.2=py39hcbf5309_0
  - jupyter_events=0.10.0=pyhd8ed1ab_0
  - jupyter_server=2.14.0=pyhd8ed1ab_0
  - jupyter_server_terminals=0.5.3=pyhd8ed1ab_0
  - jupyterlab=4.1.8=pyhd8ed1ab_0
  - jupyterlab_pygments=0.3.0=pyhd8ed1ab_1
  - jupyterlab_server=2.27.1=pyhd8ed1ab_0
  - jupyterlab_widgets=3.0.10=pyhd8ed1ab_0
  - keras=2.10.0=pyhd8ed1ab_0
  - krb5=1.20.1=h6609f42_0
  - libabseil=20220623.0=cxx17_h1a56200_6
  - libaec=1.1.3=h63175ca_0
  - libblas=3.9.0=22_win64_mkl
  - libcblas=3.9.0=22_win64_mkl
  - libcurl=8.1.2=h68f0423_0
  - libevent=2.1.10=h6a571f8_4
  - libffi=3.4.2=h8ffe710_5
  - libhwloc=2.10.0=default_h2fffb23_1000
  - libiconv=1.17=hcfcfb64_2
  - libjpeg-turbo=2.1.4=hcfcfb64_0
  - liblapack=3.9.0=22_win64_mkl
  - libpng=1.6.43=h19919ed_0
  - libprotobuf=3.20.3=h12be248_0
  - libsodium=1.0.18=h8d14728_1
  - libsqlite=3.45.3=hcfcfb64_0
  - libssh2=1.10.0=h680486a_3
  - libxcb=1.15=hcd874cb_0
  - libxml2=2.12.6=hc3477c8_2
  - libzlib=1.2.13=hcfcfb64_5
  - lz4-c=1.9.4=hcfcfb64_0
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gmp=6.1.0=2
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - markdown=3.6=pyhd8ed1ab_0
  - markupsafe=2.1.5=py39ha55989b_0
  - matplotlib-inline=0.1.7=pyhd8ed1ab_0
  - mistune=3.0.2=pyhd8ed1ab_0
  - mkl=2024.1.0=h66d3029_692
  - msys2-conda-epoch=20160418=1
  - multidict=6.0.5=py39ha55989b_0
  - nbclient=0.10.0=pyhd8ed1ab_0
  - nbconvert=7.16.4=hd8ed1ab_0
  - nbconvert-core=7.16.4=pyhd8ed1ab_0
  - nbconvert-pandoc=7.16.4=hd8ed1ab_0
  - nbformat=5.10.4=pyhd8ed1ab_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_0
  - notebook=7.1.3=pyhd8ed1ab_0
  - notebook-shim=0.2.4=pyhd8ed1ab_0
  - numpy=1.26.4=py39hddb5d58_0
  - oauthlib=3.2.2=pyhd8ed1ab_0
  - openssl=1.1.1w=hcfcfb64_0
  - opt_einsum=3.3.0=pyhc1e730c_2
  - orc=1.7.4=h623e30f_1
  - overrides=7.7.0=pyhd8ed1ab_0
  - packaging=24.0=pyhd8ed1ab_0
  - pandoc=3.2=h57928b3_0
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - parso=0.8.4=pyhd8ed1ab_0
  - pickleshare=0.7.5=py_1003
  - pip=24.0=pyhd8ed1ab_0
  - pkgutil-resolve-name=1.3.10=pyhd8ed1ab_1
  - platformdirs=4.2.1=pyhd8ed1ab_0
  - prometheus_client=0.20.0=pyhd8ed1ab_0
  - prompt-toolkit=3.0.42=pyha770c72_0
  - prompt_toolkit=3.0.42=hd8ed1ab_0
  - protobuf=3.20.3=py39hcbf5309_1
  - psutil=5.9.8=py39ha55989b_0
  - pthread-stubs=0.4=hcd874cb_1001
  - pthreads-win32=2.9.1=hfa6e2cd_3
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - pyasn1=0.6.0=pyhd8ed1ab_0
  - pyasn1-modules=0.4.0=pyhd8ed1ab_0
  - pycparser=2.22=pyhd8ed1ab_0
  - pygments=2.18.0=pyhd8ed1ab_0
  - pyjwt=2.8.0=pyhd8ed1ab_1
  - pyopenssl=23.2.0=pyhd8ed1ab_1
  - pysocks=1.7.1=pyh0701188_6
  - python=3.9.15=h0269646_0_cpython
  - python-dateutil=2.9.0=pyhd8ed1ab_0
  - python-fastjsonschema=2.19.1=pyhd8ed1ab_0
  - python-flatbuffers=24.3.25=pyh59ac667_0
  - python-json-logger=2.0.7=pyhd8ed1ab_0
  - python_abi=3.9=4_cp39
  - pytz=2024.1=pyhd8ed1ab_0
  - pyu2f=0.1.5=pyhd8ed1ab_0
  - pywin32=306=py39h99910a6_2
  - pywinpty=2.0.13=py39h99910a6_0
  - pyyaml=6.0.1=py39ha55989b_1
  - pyzmq=26.0.3=py39h03e5c00_0
  - qtconsole-base=5.5.2=pyha770c72_0
  - qtpy=2.4.1=pyhd8ed1ab_0
  - re2=2022.06.01=h0e60522_1
  - referencing=0.35.1=pyhd8ed1ab_0
  - requests=2.31.0=pyhd8ed1ab_0
  - requests-oauthlib=2.0.0=pyhd8ed1ab_0
  - rfc3339-validator=0.1.4=pyhd8ed1ab_0
  - rfc3986-validator=0.1.1=pyh9f0ad1d_0
  - rpds-py=0.18.1=py39h92a245a_0
  - rsa=4.9=pyhd8ed1ab_0
  - scipy=1.13.0=py39h1a10956_1
  - send2trash=1.8.3=pyh5737063_0
  - setuptools=69.5.1=pyhd8ed1ab_0
  - six=1.16.0=pyh6c4a22f_0
  - snappy=1.1.10=hfb803bf_1
  - sniffio=1.3.1=pyhd8ed1ab_0
  - soupsieve=2.5=pyhd8ed1ab_1
  - sqlite=3.45.3=hcfcfb64_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - tbb=2021.12.0=h91493d7_0
  - tensorboard=2.10.1=pyhd8ed1ab_0
  - tensorboard-data-server=0.6.1=py39hcbf5309_4
  - tensorboard-plugin-wit=1.8.1=pyhd8ed1ab_0
  - tensorflow=2.10.0=mkl_py39ha510bab_0
  - tensorflow-base=2.10.0=mkl_py39h6a7f48e_0
  - tensorflow-estimator=2.10.0=py39haa95532_0
  - termcolor=2.4.0=pyhd8ed1ab_0
  - terminado=0.18.1=pyh5737063_0
  - tinycss2=1.3.0=pyhd8ed1ab_0
  - tk=8.6.13=h5226925_1
  - tomli=2.0.1=pyhd8ed1ab_0
  - tornado=6.4=py39ha55989b_0
  - traitlets=5.14.3=pyhd8ed1ab_0
  - types-python-dateutil=2.9.0.20240316=pyhd8ed1ab_0
  - typing-extensions=4.11.0=hd8ed1ab_0
  - typing_extensions=4.11.0=pyha770c72_0
  - typing_utils=0.1.0=pyhd8ed1ab_0
  - ucrt=10.0.22621.0=h57928b3_0
  - uri-template=1.3.0=pyhd8ed1ab_0
  - urllib3=2.2.1=pyhd8ed1ab_0
  - vc=14.3=hcf57466_18
  - vc14_runtime=14.38.33130=h82b7239_18
  - vs2015_runtime=14.38.33130=hcb4865c_18
  - wcwidth=0.2.13=pyhd8ed1ab_0
  - webcolors=1.13=pyhd8ed1ab_0
  - webencodings=0.5.1=pyhd8ed1ab_2
  - websocket-client=1.8.0=pyhd8ed1ab_0
  - werkzeug=3.0.3=pyhd8ed1ab_0
  - wheel=0.43.0=pyhd8ed1ab_1
  - widgetsnbextension=4.0.10=pyhd8ed1ab_0
  - win_inet_pton=1.1.0=pyhd8ed1ab_6
  - winpty=0.4.3=4
  - wrapt=1.16.0=py39ha55989b_0
  - xorg-libxau=1.0.11=hcd874cb_0
  - xorg-libxdmcp=1.1.3=hcd874cb_0
  - xz=5.2.6=h8d14728_0
  - yaml=0.2.5=h8ffe710_2
  - yarl=1.9.4=py39ha55989b_0
  - zeromq=4.3.5=he0c23c2_3
  - zipp=3.17.0=pyhd8ed1ab_0
  - zlib=1.2.13=hcfcfb64_5
  - zstd=1.5.6=h0ea2cb4_0
  - pip:
      - tensorflow==2.10.0
      - altair==5.3.0
      - backcall==0.2.0
      - build==1.2.1
      - cachecontrol==0.14.0
      - cleo==2.1.0
      - crashtest==0.4.1
      - distlib==0.3.8
      - docopt==0.6.2
      - dulwich==0.21.7
      - filelock==3.14.0
      - gitdb==4.0.11
      - gitpython==3.1.43
      - installer==0.7.0
      - ipython==8.12.3
      - jaraco-classes==3.4.0
      - keyring==24.3.1
      - markdown-it-py==3.0.0
      - mdurl==0.1.2
      - more-itertools==10.2.0
      - msgpack==1.0.8
      - pandas==2.2.2
      - pexpect==4.9.0
      - pillow==10.3.0
      - pipreqs==0.5.0
      - pkginfo==1.10.0
      - poetry==1.8.3
      - poetry-core==1.9.0
      - poetry-plugin-export==1.8.0
      - ptyprocess==0.7.0
      - pyarrow==16.0.0
      - pydeck==0.9.1
      - pyproject-hooks==1.1.0
      - pywin32-ctypes==0.2.2
      - rapidfuzz==3.9.0
      - rawpy==0.19.1
      - requests-toolbelt==1.0.0
      - rich==13.7.1
      - shellingham==1.5.4
      - smmap==5.0.1
      - streamlit==1.33.0
      - tenacity==8.3.0
      - toml==0.10.2
      - tomlkit==0.12.5
      - toolz==0.12.1
      - trove-classifiers==2024.4.10
      - tzdata==2024.1
      - virtualenv==20.26.1
      - watchdog==4.0.0
      - wxpython==4.2.1
      - yarg==0.1.9
prefix: C:\Users\user\anaconda3\envs\imageclassenv2
