[tool.poetry]
name = "image-app-deployment"
version = "0.1.0"
description = "A streamlit app that uses deep learning to classify and save images into different categorical folder."
authors = ["ghadieh279 <ghadiehmohammad@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "3.11"
gobject==0.1.0
rawpy==0.19.1
streamlit<1.35.0
tensorflow==2.10.0
wheel~=0.43.0
attrdict==2.0.1
attrdict3==2.0.2
Pillow==10.3.0
wxPython~=4.2.1

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
