[tool.poetry]
name = "image-app-deployment"
version = "0.1.0"
description = "A streamlit app that uses deep learning to classify and save images into different categorical folder."
authors = ["ghadieh279 <ghadiehmohammad@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "3.9"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
